name: MChat
main: com.miraclem4n.mchat.MChat
version: ${version}-${build.number}
author: MiracleM4n
authors: [MiracleM4n]
website: http://mdev.in/
thread: http://forums.bukkit.org/threads/22958/
softdepend: [GroupManager, PermissionsBukkit, bPermissions, PermissionsEx, GeoIPTools, Vault]
description: Chat Formatting for Bukkit
commands:
    mchat:
        usage: |
            [MChat] Help Screen
            - /<command> reload config = Reload Config.
            - /<command> reload info = Reload Info.
            - /<command> reload censor = Reload Censor.
            - /<command> reload locale = Reload Locale.
            - /<command> reload all = Reload All Configs.
            - /<command> version = Show mChatSuite Version.
        aliases: [mchatsuite]
        ~permissions: mchat.reload.*
    mchatuser:
        usage: |
            /<command> = Show Info User Help.
        aliases: [muser]
        ~permissions: mchat.user.*
    mchatgroup:
        usage: |
            /<command> = Show Info Group Help.
        aliases: [mgroup]
        ~permissions: mchat.group.*
    mchatme:
        usage: |
            /<command> *Message* - Displays message.
        aliases: [mme]
        ~permissions: mchat.group.*
permissions:
    mchat.*:
        default: op
        description: Allows full use of mChat.
        children:
            mchat.reload.*: true
            mchat.suppress.*: true
            mchat.bypass.*: true
            mchat.user.*: true
            mchat.group.*: true
            mchat.coloredchat: true
            mchat.censorbypass: true
            mchat.me: true
            mchat.version: true
            mchat.spy: true
    mchat.reload.*:
        default: false
        description: Allow usage of /mchat reload '[config/info/censor/locale/all]'
        children:
            mchat.reload.config: true
            mchat.reload.info: true
            mchat.reload.censor: true
            mchat.reload.locale: true
            mchat.reload.all: true
    mchat.suppress.*:
        default: false
        description: Allow usage suppression of all messages.
        children:
            mchat.suppress.join: true
            mchat.suppress.quit: true
            mchat.suppress.kick: true
    mchat.bypass.*:
        default: false
        description: Allow bypass of all Automatic functions.
        children:
            mchat.bypass.afk: true
            mchat.bypass.afkkick: true
            mchat.bypass.suppress.*: true
            mchat.bypass.clock: true
    mchat.bypass.suppress.*:
        default: false
        description: Allow bypass of all Override functions.
        children:
            mchat.bypass.suppress.join: true
            mchat.bypass.suppress.quit: true
            mchat.bypass.suppress.kick: true
    mchat.user.*:
        default: false
        description: Allows full use of all user info related mChat commands.
        children:
            mchat.user.add.*: true
            mchat.user.set.*: true
            mchat.user.remove.*: true
    mchat.group.*:
        default: false
        description: Allows full use of all group info related mChat commands.
        children:
            mchat.group.add.*: true
            mchat.group.remove.*: true
    mchat.user.add.*:
        default: false
        description: Allows full use of all user info add mChat commands.
        children:
            mchat.user.add.player: true
            mchat.user.add.ivar: true
            mchat.user.add.world: true
            mchat.user.add.wvar: true
    mchat.user.set.*:
        default: false
        description: Allows full use of all user info set mChat commands.
        children:
            mchat.user.set.group: true
    mchat.user.remove.*:
        default: false
        description: Allows full use of all user info remove mChat commands.
        children:
            mchat.user.remove.player: true
            mchat.user.remove.ivar: true
            mchat.user.remove.world: true
            mchat.user.remove.wvar: true
    mchat.group.add.*:
        default: false
        description: Allows full use of all group info add mChat commands.
        children:
            mchat.group.add.group: true
            mchat.group.add.ivar: true
            mchat.group.add.world: true
            mchat.group.add.wvar: true
    mchat.group.remove.*:
        default: false
        description: Allows full use of all group info remove mChat commands.
        children:
            mchat.group.remove.group: true
            mchat.group.remove.ivar: true
            mchat.group.remove.world: true
            mchat.group.remove.wvar: true
    mchat.reload.config:
        default: false
        description: Allow usage of /mchat reload config
    mchat.reload.info:
        default: false
        description: Allow usage of /mchat reload info
    mchat.reload.censor:
        default: false
        description: Allow usage of /mchat reload censor
    mchat.reload.locale:
        default: false
        description: Allow usage of /mchat reload locale
    mchat.reload.all:
        default: false
        description: Allow usage of /mchat reload all
    mchat.coloredchat:
        default: false
        description: Allow colour in chat messages.
    mchat.censorbypass:
        default: false
        description: Allow bypass of msg censoring.
    mchat.me:
        default: false
        description: Allow use of the /mchatme command.
    mchat.version:
        default: false
        description: Allow use of the /mchat version command.
    mchat.spy:
        default: false
        description: Allows player to view all chat messages.
    mchat.suppress.join:
        default: false
        description: Allow suppression of the mChat Join Messages.
    mchat.suppress.quit:
        default: false
        description: Allow suppression of the mChat Quit Messages.
    mchat.suppress.kick:
        default: false
        description: Allow suppression of the mChat Kick Messages.
    mchat.bypass.suppress.join:
        default: false
        description: Allow bypassing of Join Suppression.
    mchat.bypass.suppress.quit:
        default: false
        description: Allow bypassing of Quit Suppression.
    mchat.bypass.suppress.kick:
        default: false
        description: Allow bypassing of Kick Suppression.
    mchat.user.add.player:
        default: false
        description: Allow usage of /mchatuser add player Player
    mchat.user.add.ivar:
        default: false
        description: Allow usage of /mchatuser add ivar Player InfoVariable InfoValue
    mchat.user.add.world:
        default: false
        description: Allow usage of /mchatuser add world Player World
    mchat.user.add.wvar:
        default: false
        description: Allow usage of /mchatuser add world Player World InfoVariable InfoValue
    mchat.user.set.group:
        default: false
        description: Allow usage of /mchatuser set group Player NewGroup
    mchat.user.remove.player:
        default: false
        description: Allow usage of /mchatuser remove Player
    mchat.user.remove.ivar:
        default: false
        description: Allow usage of /mchatuser remove Player InfoVariable
    mchat.user.remove.world:
        default: false
        description: Allow usage of /mchatuser remove Player World
    mchat.user.remove.wvar:
        default: false
        description: Allow usage of /mchatuser remove Player World InfoVariable
    mchat.group.add.group:
        default: false
        description: Allow usage of /mchatgroup add group Group
    mchat.group.add.ivar:
        default: false
        description: Allow usage of /mchatgroup add ivar Group InfoVariable InfoValue
    mchat.group.add.world:
        default: false
        description: Allow usage of /mchatgroup add world Group World
    mchat.group.add.wvar:
        default: false
        description: Allow usage of /mchatgroup add world Group World InfoVariable InfoValue
    mchat.group.remove.group:
        default: false
        description: Allow usage of /mchatgroup remove group Group
    mchat.group.remove.ivar:
        default: false
        description: Allow usage of /mchatgroup remove ivar Group InfoVariable
    mchat.group.remove.world:
        default: false
        description: Allow usage of /mchatgroup remove world Group World
    mchat.group.remove.wvar:
        default: false
        description: Allow usage of /mchatgroup remove wvar Group World InfoVariable
